config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      get 'languages/:username' => 'languages#show'
    end
  end
  get 'languages' => 'languages#show'

  root to: 'languages#index'
end

app/models/api_error_response.rb
class ApiErrorResponse < ApiResponse
  def success?
    false
  end

  def failure?
    !success
  end
end

app/models/api_request.rb
require 'httpclient'

class ApiRequest
  attr_reader :username, :http_client

  def initialize(username)
    @username = username
    @http_client = HTTPClient.new
  end

  def call
    http_response = http_client.get(request_uri)
    ApiResponse.from_http_response(http_response)
  end

  private

  def request_uri
    "https://api.github.com/users/#{username}/repos"
  end

end

app/models/api_response.rb
class ApiResponse
  def self.from_http_response(http_response)
    new(
      status: http_response.http_header.status_code,
      body: http_response.body
    )
    end

  attr_reader :status, :body

  def initialize(status:, body:)
    @status = status
    @body = body
  end

  def success?
    status == 200
  end

  private

end

app/models/parser.rb
class Parser
  def self.parse(response)
    new(response).parse
  end

  def initialize(response)
    @response = response
    @data = JSON.parse(response.body)
  end

  def parse
    response.success? ? parse_response : format_error
  end

  private
  attr_reader :response, :data

  def parse_response
    message = (data.count == 0) ? "No public repos" : parse_repos
    { status: 200, message: message }
  end

  def format_error
    {status: response.status, message: data["message"]}
  end

  def parse_repos
    data
      .map {|repo| repo['language'] }
      .group_by{|lang| lang}
      .reject{|k,v| k.nil?}
      .max_by{|lang| lang.last.length}[0]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  
  def index
  end

  def show
    if valid?(params[:username])
      response = ApiRequest.new(params[:username]).call
      @results = Parser.parse(response)
    else
      @results = {status: 400, message: "Invalid username"}
    end   
  end

  private
  def valid?(username)
    regex = Regexp.new(/^[a-z,A-Z][\w-]{2,25}$/)
    regex.match(username)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/languages/index.html.haml
%body
  .wrapper
    %p Enter a github username to discover the user's preferred language

    =form_tag(languages_path, method: 'get') do
      %label{for: 'username'} Username:
      %input{type: 'text', name: 'username'}
      %input{type: 'submit', value: 'Show language'}

app/views/languages/show.html.haml
=@results[:message]

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title GitLanguage
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield